sudo: false

language: java

jdk:
  - openjdk8
  
env:
  global:
  - SONATYPE_USERNAME=ralscha23
  - secure: XDuZnWZJl9UM7fq2Idgq0duKCsbFjYFG2mRmsM4Ak0L8lvnuDftrTmaa/x1Hh158VTnKVmhNJ0qpLGulN67vjNOG6mgUXiq2q+VlqqHlPF4+22bKXMOgvH+AN2Qu7xMAcQ5k7gbNQQ2W/xhZIDx81O20c3lRL3QEdF3Y0hGiPsI=

after_success:
- python addsettings.py
- mvn clean deploy -DskipTests=true --settings ~/.m2/mySettings.xml

cache:
  directories:
  - $HOME/.m2